### ISSUE TITLE
[NOT_AN_ISSUE]Please consider to use FreeType font rasterizer

### ISSUE THREAD

**Issue by bagobor** [BalazsJako/ImGuiColorTextEdit#1]
1. Awesome work!

2. PTAL at https://github.com/ocornut/imgui_club/tree/master/imgui_freetype
It has hinting support so it will result in better text render quality.
(you'll find screenshots here: https://github.com/ocornut/imgui/issues/618)

**Comment by BalazsJako** [comment]
1. Thank you. :)

2. You mean for screenshots? Because this widget uses the font tenderer whatever ImGui uses. So it is on the user to pick the font renderer he or she wants.

**Comment by bagobor** [comment]
1. you are welcome
2. yes, for screenshots and for demo app. :)
