### ISSUE TITLE
Incredibly Slow Editor Responsiveness

### ISSUE THREAD

**Issue by atom0s** [BalazsJako/ImGuiColorTextEdit#104]
Hello, firstly great addon for ImGui, I am very interested in using this in something I am working on now. However, I am running into an issue with the editor being incredibly slow to respond to any input. 

Using the current repo and your linked example DX11 project, the default file loaded is ~2700 lines. When trying to do anything in the file to test out the editor, every single keystroke takes upwards of 5-10 seconds to register. 

I've narrowed it down to the following call making all the lag happen:
```
void TextEditor::ColorizeInternal()
```

If I completely stop this from running, lag is gone but obviously coloring dies. I get the same level of speed/responsiveness regardless of the editor syntax used. I know there are mentions of the C/C++ syntax supposably being much faster, but for me, all included syntaxes yield the same result of being super slow.

(Side note, the speed/slowdown relates to the size of the file/text being edited. As more data is added to the editor, the more it slows down. It's somewhat usable at around 900-1000 lines of the default code that is loaded into it, but anything higher generally makes it crawl to do anything for me.)

**Comment by BalazsJako** [comment]
Hi, is this issue coming on a debug or a release build?
Debug builds are significantly slower than release, especially with regexp-based colouring, but it supposed to run reasonably fast on release builds, even with regexp.

**Comment by atom0s** [comment]
Ah, does appear to be a debug mode side effect. I have managed to get the performance up a lot in debug mode when specifically testing the editor though for my cases.

In TextEditor.cpp (and other required places) adding the following defines to the top of the files:
```cpp
#define _ITERATOR_DEBUG_LEVEL 0
#define _ITERATOR_DEBUG_ARRAY_OVERLOADS 0
#define _ENHANCED_REGEX_VISUALIZER 0
```

For compiler settings:

 - Using VS2019
 - Using C++17 Standard
 - Change debug information format to 'Program Database (/Zi)
 - Enable String Pooling (/GF)
 - Enable C++ Exceptions (/EHa)

At this point, the debug performance is fairly decent and usable while testing things. I'd suggest adding the defines in a custom define block used specifically for testing this addon vs. always having it enabled as it does disable a lot of useful debug related information for other things throughout the STL when it's set up like this.
