### ISSUE TITLE
bug with colorizing line with an error marker when scrolling horizontally

### ISSUE THREAD

**Issue by onqtam** [BalazsJako/ImGuiColorTextEdit#12]
Notice how the red marking goes to the left when I scroll to the right

![1](https://user-images.githubusercontent.com/4648169/34920196-881b609c-f977-11e7-8eb8-87d519e0ccb4.png)
![2](https://user-images.githubusercontent.com/4648169/34920197-8835e6b0-f977-11e7-97a3-9d6ca1eabaca.png)

**Comment by BalazsJako** [comment]
Fixed. :)
