### ISSUE TITLE
Suggestion: Ctrl + Backspace

### ISSUE THREAD

**Issue by Zawaer** [BalazsJako/ImGuiColorTextEdit#138]
When pressing Ctrl + Backspace, it deletes last word instead of inserting space

![](https://c.tenor.com/r2x4Kv8ftF4AAAAC/control-backspace.gif)

**Comment by santaclose** [comment]
made a pull request including this and Ctrl delete #143

**Comment by Zawaer** [comment]
@santaclose Wow, thanks!
