### ISSUE TITLE
With global font scale?

### ISSUE THREAD

**Issue by paladin-t** [BalazsJako/ImGuiColorTextEdit#14]
This is a nice addon. I got a question when using it. Should `io.FontGlobalScale` be counted here:

https://github.com/BalazsJako/ImGuiColorTextEdit/blob/b23fb4a1b855c59367085931268f470ae514c877/TextEditor.cpp#L379

Thanks.

**Comment by BalazsJako** [comment]
Yes, you are right. Fixed.
