### ISSUE TITLE
The Color Highlight of identifiers gets removed on the 10th line

### ISSUE THREAD

**Issue by aurhack** [BalazsJako/ImGuiColorTextEdit#146]
For some reason that happens and it's super annoying
![image](https://user-images.githubusercontent.com/72323046/209587878-60ebe340-7d57-474e-a2d8-8ba01d5e5b1a.png)

Anyone knows the fix?

**Comment by ciprinicu** [comment]
Same issue here, any fix?

**Comment by aurhack** [comment]
Hello, i fixed it entering on SetLanguage function and removed the Colorize
function call

**Comment by ciprinicu** [comment]
Thank you very mutch! Fixed.
