### ISSUE TITLE
make it compile with gcc

### ISSUE THREAD

**Issue by onqtam** [BalazsJako/ImGuiColorTextEdit#17]
with GCC the ```<cmath>``` header needs to be included for ```floor()``` in the .cpp - [this PR](https://github.com/BalazsJako/ImGuiColorTextEdit/pull/7) fixes that.

Currently I have a workaround in a demo project (as can be seen [here](https://github.com/onqtam/rcrl/blob/502ad6dd53f2827e153bfd2193211e33ab303dbc/CMakeLists.txt#L114)) which I would like to remove so that the code is simpler - people will be looking at it when I make an official release of that example project.

**Comment by BalazsJako** [comment]
PR merged, thank you :)
