### ISSUE TITLE
pasting from clipboard when inputting an underscore '_'

### ISSUE THREAD

**Issue by onqtam** [BalazsJako/ImGuiColorTextEdit#18]
So in my setup whenever I write ```_``` (Shift + ```-```) I get everything from my clipboard pasted in addition to the underscore character written. This is because of [this code](https://github.com/BalazsJako/ImGuiColorTextEdit/blob/f49aa9abc6fd66648b428b4a8bc394e01bbd3f4b/TextEditor.cpp#L440). What is the purpose behind pasting with ```_```?

The ASCII code of ```-``` is 45 - is it supposed to be something else?

I also tested this with the [demo project ](https://github.com/BalazsJako/ColorTextEditorDemo) and it doesn't get triggered there - any idea why?

I'm using [this code from the examples of imgui for opengl2 and glfw](https://github.com/ocornut/imgui/blob/8d54b1b7aff34111b6f64c0e076eb0b7a981ad9a/examples/opengl2_example/imgui_impl_glfw.cpp)

**Comment by onqtam** [comment]
I investigated further. When using the imgui/opengl/glfw integration code from the imgui [examples](https://github.com/ocornut/imgui/tree/master/examples) the problem is there. When using DirectX integration from the [examples](https://github.com/ocornut/imgui/tree/master/examples) - this problem doesn't exist.

I won't do any further investigation since I solved my issue with a simple dirty [hack](https://github.com/onqtam/rcrl/commit/8ef887cc1736eea189acf394a90297e5de96549a)

**Comment by dmitrygerasimuk** [comment]
There were a line in TextEditor.cpp, isn't that you were looking for?     

     else if (!IsReadOnly() && !ctrl && shift && !alt && ImGui::IsKeyPressed(45))
     Copy();

**Comment by onqtam** [comment]
@dmitrygerasimuk  yes but I'm not sure why it's there so I cannot recommend any further action

**Comment by BalazsJako** [comment]
Cannot reproduce. My best guess is that the '-' character and the INS key are mapped to the same value. It works fine on my Windows/DX11 config. Can you please check that?

**Comment by onqtam** [comment]
Yes - with the DX code from imgui everything is fine - bug with glfw it is not.

With glfw the insert key doesn't work for me - but pressing ```-``` is what is 45...

I did the following:

```auto lets_see = ImGui::GetKeyIndex(ImGuiKey_Insert);``` - and the value of ```lets_see``` is 260 on my setup. Perhaps using ```ImGui::GetKeyIndex(ImGuiKey_Insert)``` instead of ```45``` would be the more portable solution?

**Comment by BalazsJako** [comment]
Of course. My only problem is that my setup does not have that symbol... I have to update my copy of ImGui I think....

**Comment by onqtam** [comment]
note that there were some changes in the setup API a few months ago so u might have to consult the current directX examples in imgui

**Comment by marcel303** [comment]
I was running into the same problem. I'm using my own ImGui integration code and key codes for V, C, etc were also broken for me. Since the editornow compiles against a more recent version of ImGui I think the key mapping symbols for C, V, X, Y, Insert should be available? Pull request https://github.com/BalazsJako/ImGuiColorTextEdit/pull/49 fixes the key mappings, including the use of the insert key.

**Comment by BalazsJako** [comment]
I think it is fixed already. Feel free to reopen it if you still have the problem.
