### ISSUE TITLE
Text changed return value from Render?

### ISSUE THREAD

**Issue by Unit2Ed** [BalazsJako/ImGuiColorTextEdit#20]
It would be useful to be able to receive information about when the text has been changed (eg to trigger a Lua script load to check for errors in realtime).

Naively, this could be done by the user comparing GetText() with the previous value, but it's a bit of a sledgehammer approach.

Better would be implemented with a "text changed" member bool that's set inside any text manipulation function that adjusts the undo index. The flag would be returned and cleared at the end of Render().

**Comment by BalazsJako** [comment]
Done. Added IsTextChanged() function. It will report the same value until the next Render() call, so you can call it from anywhere multiple times if you want to.
