### ISSUE TITLE
SelectAll fails to do anything when there's only one line 

### ISSUE THREAD

**Issue by Unit2Ed** [BalazsJako/ImGuiColorTextEdit#21]
`SetSelection(Coordinates(0, 0), Coordinates((int)mLines.size(), 0));`
Would resolve to Coordinates(0,0), Coordinates(**1**,0), which is then sanitised by SetSelection to Coordinates(0,0),Coordinates(**0**,0), resulting in no selection as the end coord is beyond the end of the document.

I've fixed this locally by changing it to select the last character of the last line instead of the line beyond the end of the document:

```
void TextEditor::SelectAll()
{
	if(!mLines.empty())
		SetSelection(Coordinates(0, 0), Coordinates((int)mLines.size()-1, mLines.back().size()));
}
```

**Comment by BalazsJako** [comment]
Fixed now, please test. Actually SanitizeCoordinates was the culprit, setting the column to zero if the input was pointing beyond the end of the text.
