### ISSUE TITLE
Is there supposed to be some way to append a new line(Enter)?

### ISSUE THREAD

**Issue by cheako** [BalazsJako/ImGuiColorTextEdit#24]
My [project](https://github.com/cheako/cheako-vulkan/tree/f3e8b98d774f17d1f099d678933da24ecce95a5e/013editor) builds and runs, but the enter key does not feed a line and return the carrage.

I've [installed the callbacks](https://github.com/cheako/cheako-vulkan/blob/f3e8b98d774f17d1f099d678933da24ecce95a5e/013editor/libdata.c#L348) and [passed on keypresses](https://github.com/cheako/cheako-vulkan/blob/f3e8b98d774f17d1f099d678933da24ecce95a5e/013editor/libdata.c#L25).

**Comment by BalazsJako** [comment]
You should forward newline characters into ImGui's keyboard character queue  (ImGui_IO::InputCharacters). The editor will fetch and process them.
