### ISSUE TITLE
Triple left-click should select whole line.

### ISSUE THREAD

**Issue by cheako** [BalazsJako/ImGuiColorTextEdit#25]
Also it would be grand if the double-click glob chars could be changed, I'm thinking about ":" specifically.  In passwd and shadow files It's great to stop at : but for "scp host:file ." it's unfortunate.

**Comment by BalazsJako** [comment]
Triple left-click works now. The word selection mode works by scanning from the cursor position up to the  character in the text which still has the same associated palette index (keyword, number, etc.). That index  comes from the colorizer, so if you want to select host:file as a whole word, you should specify that in your language definition as a whole identifier or any other category.
