### ISSUE TITLE
TextEditor::Glyph::mColorIndex is too small.

### ISSUE THREAD

**Issue by cheako** [BalazsJako/ImGuiColorTextEdit#26]
```
g++ -I../cimgui/imgui -I../../include   -c -o TextEditor.o TextEditor.cpp
In file included from TextEditor.cpp:7:0:
TextEditor.h:125:30: warning: ‘TextEditor::Glyph::mColorIndex’ is too small to hold all values of ‘enum class TextEditor::PaletteIndex’
   PaletteIndex mColorIndex : 7;
```

This is on i686, 32bit linux.

**Comment by johanwendin** [comment]
@cheako - you might want to search through open issues before posting. (and possibly gather your thoughts up into a few issues instead of creating a ton of one-line issues)

This issue has already been reported here: https://github.com/BalazsJako/ImGuiColorTextEdit/issues/11
