### ISSUE TITLE
Small issue with fonts

### ISSUE THREAD

**Issue by Skyway666** [BalazsJako/ImGuiColorTextEdit#54]
![image](https://user-images.githubusercontent.com/16372100/49280358-45e37980-f48a-11e8-870d-61764e42bde1.png)

Hi, I hope you can read that :). I encountered a little problem with fonts, it looks like you use the first one in the array of fonts in ImGui, and if you are using different fonts that doesn't seem to work... 
```
void TextEditor::Render(const char* aTitle, const ImVec2& aSize, bool aBorder)
{
	mWithinRender = true;

	ImGuiIO& io = ImGui::GetIO();
	auto xadv = (io.Fonts->Fonts[0]->IndexAdvanceX['X']);
	mCharAdvance = ImVec2(xadv, io.Fonts->Fonts[0]->FontSize + mLineSpacing);
```
My solution was passing the used font as an argument in the "Render" function, although I think that it'd be better to acces the currently used font from the ImGui io.

```
void TextEditor::Render(const char* aTitle,ImFont* font, const ImVec2& aSize, bool aBorder)
{
	mWithinRender = true;

	ImGuiIO& io = ImGui::GetIO();
	auto xadv = (font->IndexAdvanceX['X']);
	mCharAdvance = ImVec2(xadv, font->FontSize + mLineSpacing);

```

Having said that, your API i great, the fact that you can make custom colors for different languages is really good. I'll make one for "wren", and pass it to you in case you want to merge it with the source code.

**Comment by BalazsJako** [comment]
Oh, right, it seems reasonable at first sight, A small detail I left unelaborated.  Thanks for pointing it out.
I am glad you found the editor useful. :)

**Comment by BalazsJako** [comment]
Uhm.... I have checked this, and it is already fixed. Have you checked the latest rev? It uses the current font, whatever it is.
