### ISSUE TITLE
Return key

### ISSUE THREAD

**Issue by procfxgen** [BalazsJako/ImGuiColorTextEdit#6]
Return key does not work for me ...

**Comment by procfxgen** [comment]
ok i found it !

In ImGui_ImplSdl_ProcessEvent() function

I need to add Return key to io.InputChar

        ...
        case SDL_KEYUP:
	{
		int key = event->key.keysym.sym & ~SDLK_SCANCODE_MASK;
		io.KeysDown[key] = (event->type == SDL_KEYDOWN);
		io.KeyShift = ((SDL_GetModState() & KMOD_SHIFT) != 0);
		io.KeyCtrl = ((SDL_GetModState() & KMOD_CTRL) != 0);
		io.KeyAlt = ((SDL_GetModState() & KMOD_ALT) != 0);
		io.KeySuper = ((SDL_GetModState() & KMOD_GUI) != 0);

		if (event->key.keysym.scancode == SDL_SCANCODE_RETURN && event->type == SDL_KEYDOWN)
			io.AddInputCharactersUTF8("\r");

		return true;
	}

**Comment by BalazsJako** [comment]
Yes, it is treated as any other character.

**Comment by onqtam** [comment]
Hi!

Return doesn't work for me either (using the glfw setup code from the imgui project - as seen [here](https://github.com/ocornut/imgui/blob/master/examples/opengl2_example/imgui_impl_glfw.cpp))
