### ISSUE TITLE
AltGr-handling

### ISSUE THREAD

**Issue by johanwendin** [BalazsJako/ImGuiColorTextEdit#61]
in:
```void TextEditor::HandleKeyboardInputs()```

this row:
``` else if (!IsReadOnly() && !ctrl && !alt) ```

makes the texteditor unable to enter any characters requiring AltGr key to be pressed (coded as Ctrl+Alt in European Windows). (for instance { } [ ] etc)

Quick fix for those affected is to remove the !ctrl and !alt check.

This issue doesn't exist within ImGui's inputtext itself.

Do you reckon there's a better fix for this issue?

**Comment by BalazsJako** [comment]
I couldn't test it (no numlock support on my laptop), but it seems fine for me.

**Comment by BalazsJako** [comment]
Fixed in #79.
