### ISSUE TITLE
Colorizing lag

### ISSUE THREAD

**Issue by Unit2Ed** [BalazsJako/ImGuiColorTextEdit#70]
We've noticed that there's a lag colorizing new text - as you're typing it renders in the default color for a frame before the syntax highlighting kicks in.

It appears this is happening because when `ColorizeInternal` goes down the multi-line comment path, it `return`s rather than continuing to do the main colorization pass. This results in a two-stage process where commenting is checked on frame 1, and then syntax highlighting applies on frame 2.

Is there a reason for it being this way? I can see any bad effects after removing the `return` locally. According to blame, it's always been there.

https://github.com/BalazsJako/ImGuiColorTextEdit/blob/2aa980e18cd9376a2ce8911feb6893251088affe/TextEditor.cpp#L1951

**Comment by BalazsJako** [comment]
Tbh, it was not noticeable on my machine, but if you see no issues with it, it is ok to remove the return.
