### ISSUE TITLE
Cursor position is more off with each character on line

### ISSUE THREAD

**Issue by sadovsf** [BalazsJako/ImGuiColorTextEdit#71]
Longer the line more cursor gets off to right from place it is writing. I tried multiple fonts along with monospaced one but nothing helped. Maybe some change in recent ImGui? I'am using release of 1.68 made recently. Here is the issue visible:
![image](https://user-images.githubusercontent.com/2211533/53442093-bad23b00-3a08-11e9-9327-ddd114b8dbda.png)

Cursor is there actually at the end of the line (when i press delete last character on line dissapears)

**Comment by sadovsf** [comment]
I did try it with demo as well and there is issue visible too

**Comment by BalazsJako** [comment]
Strange. Is there any extra scaling or spacing active? It was completely fine with my last rev. I will check later.

**Comment by sadovsf** [comment]
No scale, but thanks to ImGui author i found out some more info:
https://github.com/ocornut/imgui/issues/986

It looks like he fixed some stuff in ImGui::CalcTextSize resulting in small mathematical error in your calculation now. This + rounding at the end (which iam not sure how old is) probably caused this issue. When i remove rounding and reintroduce removed code it seems to be working again

**Comment by sadovsf** [comment]
So i just confirmed that partially problem is there due to 
+ 1.0f * fontScale
With every usage of x from ImGui::CalcTextSize. That was mitigating this: https://github.com/ocornut/imgui/commit/3d20471559ddba7cebd4ee53eacc3dd06541375d code (reverted in this commit) that was -1.0f * scale every calculation.

Another error is introduced by mentioned rounding which should be possible to get rid off by using font function CalcTextSizeA right away. Will test this theory in a minute (btw awesome widget, thank you for that)

**Comment by sadovsf** [comment]
So i just confirmed that removing that and replacing usage of CalcTextSize for:
ImGui::GetFont()->CalcTextSizeA(ImGui::GetFontSize(), FLT_MAX, -1.0f, buf, nullptr, nullptr)

Pull request with fix is up ;-)

**Comment by mpue** [comment]
Thank you so much! This almost gave me a headache...;) Works perfect with different fonts and sizes.

**Comment by sadovsf** [comment]
You are welcome 😊
I needed some script editor for imgui for my personal project and fixing this seem to be faster than writing my own with probably much less features 😁 thank you for this awesome widget 😊
