### ISSUE TITLE
Shift + tab , tab , ctrl + z = "cannot seek vector iterator after end"

### ISSUE THREAD

**Issue by or75** [BalazsJako/ImGuiColorTextEdit#73]
1) Select random code (which is indented tab)
2) Shift + tab
3) Tab
4) Ctrl + z
5) Crash

![2019-03-08_19-18-01](https://user-images.githubusercontent.com/5619678/54040768-32f1eb00-41d7-11e9-8793-a7f27926fc3c.gif)

fix ?

**Comment by BalazsJako** [comment]
Fixed. Please try it now.

**Comment by or75** [comment]
Thanks, everything is working :)
