### ISSUE TITLE
curious why we are resizing here?

### ISSUE THREAD

**Issue by luxe** [BalazsJako/ImGuiColorTextEdit#74]
https://github.com/BalazsJako/ImGuiColorTextEdit/blob/b4a074b075d861e39af08603a09dd2b728f40ae2/TextEditor.cpp#L534

I'm basically using similar logic, but I'm not sure whether I need the resize there at the end.  
Any advice on why you have it there?

**Comment by luxe** [comment]
oh, i think the buffer will infinitely grow if I don't

**Comment by BalazsJako** [comment]
Honesty, I cannot remember, but it looks like a boilerplate code. I have checked other codes, and yes, it is for clearing the input after processing.
