### ISSUE TITLE
WantCaptureKeyboard and WantTextInput problems from ImGuiIO

### ISSUE THREAD

**Issue by onqtam** [BalazsJako/ImGuiColorTextEdit#8]
When a code editor widget is focused and has a cursor inside of it - querying ```ImGui::GetIO().WantCaptureKeyboard``` or ```ImGui::GetIO().WantTextInput``` (or maybe both) should return ```true``` instead of ```false```. Also not sure about ```WantCaptureMouse``` and the rest such flags.

Great project btw! Thanks for making it public!

**Comment by sherief** [comment]
+1, this is something my UI code relies on a lot.

**Comment by BalazsJako** [comment]
Submitted a fix. I hope this is what you wanted. :) If it is not, let me know.

**Comment by onqtam** [comment]
cool - will test it tonight and give feedback :)

Thanks for the great project btw

**Comment by onqtam** [comment]
actually I just tested this and it works! thanks :)

**Comment by BalazsJako** [comment]
Great. :)
