### ISSUE TITLE
UTF8 support?

### ISSUE THREAD

**Issue by cesss** [BalazsJako/ImGuiColorTextEdit#81]
The readme says no UTF8 support... how far would that be on the horizon? Would it involve a lot of changes?

**Comment by BalazsJako** [comment]
It is not overly complicated, though it requires some effort to make it work properly. Since there were no requests for it, I did not try to implement it. If there is any demand for it, it might worth it.

**Comment by CallumDev** [comment]
I'd be interested in using it to edit localisation files for https://github.com/Librelancer/Librelancer
This requires UTF-8 though :D

**Comment by cesss** [comment]
I asked for it because these days I wouldn't write a text editor if it doesn't support UTF8 from the beginning (sooner or later, somebody will open a file with international characters in your editor). I tend to believe that what I really want is Scintilla (yes, a big monster) but running on a OpenGL and/or Vulkan based GUI. Partial ports of Scintilla to OpenGL and ImGui exist, but nobody has done a complete port, AFAIK.

**Comment by BalazsJako** [comment]
The motivation for this widget is to write an easy to use, user and coder friendly, simple shader/config/script/simple text editing utility, instead of a generic one which tries to cover a very wide range of features. Scintilla is much more complex because of that approach. 

I try to keep it small and simple as possible, without bloat, just like ImGui itself. Though, adding UTF-8 support might not compromise the overall simplicity too much, I guess.

**Comment by BalazsJako** [comment]
I have committed an experimental version of UTF-8 support to dev branch. Please test it. If it gets stable/complete enough I will merge it to master.

**Comment by BalazsJako** [comment]
Merged #84 to master.

**Comment by cesss** [comment]
Thanks a lot!! I didn't have the time to look at this before!! I'm in the process of inserting your Win32+DX11 demo into the SDL2 demos, as I have absolutely no idea about Microsoft APIs. I'm a bit surprised about you including the DirectInput header in the demo... what is it used for? I hope I'm doing the surgery right for transplanting it into SDL2... let's see...

**Comment by BalazsJako** [comment]
Very welcome :) As you might already figured out, the demo is basically a modified ImGui DX11 example, all the includes are coming from that code. The editor itself does not depend on anything like that. It relies on ImGui and STL.
