### ISSUE TITLE
Suggestion: move .png/large data to wiki repo

### ISSUE THREAD

**Issue by ocornut** [BalazsJako/ImGuiColorTextEdit#85]
Minor trick/suggestion: because png adds up in the git repo size.
The wiki that github offers is a separate git repo (`ImGuiColorTextEdit.wiki.git` instead of `ImGuiColorTextEdit.git`) 

What I do for imgui is I upload any images to the wiki repo and link to them from the readme instead, so the main repository doesn't grow with extra data.

**Comment by berdal84** [comment]
@ocornut Maybe git LFS can do the trick too (but keeping the image ref into the same repo) ?

**Comment by ocornut** [comment]
I believe there's no use for the end-user to even have this image locally, they want the code?

**Comment by BalazsJako** [comment]
Done.
