### ISSUE TITLE
Invalid cursor position after mouse click on line with tabulations

### ISSUE THREAD

**Issue by pinam45** [BalazsJako/ImGuiColorTextEdit#86]
## Problem

When I click on a line contening tabulations, the cursor is placed at a wrong position.

For example, calling only these two functions with the default font of ImGui:

    editor.SetText("        abcdefghijklmnopqrstuvwxyz\n\t\tabcdefghijklmnopqrstuvwxyz\n");
    editor.Render("editor", ImGui::GetContentRegionAvail(), false);

![Screenshot_20190613_172825](https://user-images.githubusercontent.com/14993771/59468942-57c2b380-8e01-11e9-8d06-e8d38b55b008.png)

If I click after the text on the first line the cursor is put at the right position (the end of the line), but if I click after the end of the second line the cursor is placed at a wrong position (as in the picture).

## Informations
- ImGui version: v1.70+, docking branch (https://github.com/ocornut/imgui/commit/596d81a973237c17008a4b64c72fa08bd380b79e)
- ImGuiColorTextEdit version: last (https://github.com/BalazsJako/ImGuiColorTextEdit/commit/e2a25206024408bf7d9839f54028c2c7bff6fdab)

**Comment by BalazsJako** [comment]
Fixed. Please test.

**Comment by pinam45** [comment]
It doesn't compile with ImGui 1.70 with ``IMGUI_DISABLE_OBSOLETE_FUNCTIONS`` defined because you changed ``ImGuiCol_ChildBg`` for ``ImGuiCol_ChildWindowBg`` in your last commit https://github.com/BalazsJako/ImGuiColorTextEdit/commit/9f8a336e0d73f78b003f7392f1871c2dd746eb9c.

https://github.com/BalazsJako/ImGuiColorTextEdit/blob/9f8a336e0d73f78b003f7392f1871c2dd746eb9c/TextEditor.cpp#L1127

``ImGuiCol_ChildWindowBg`` was renamed to ``ImGuiCol_ChildBg`` in ImGui 1.53
https://github.com/ocornut/imgui/blob/2645a2516f032332b68a66e20b3d2d8adc2490d0/imgui.h#L1070

Otherwise work well, thank you for this super useful widget.

**Comment by BalazsJako** [comment]
Welcome :)
Fixed the ImGuiCol_ChildWindowBg issue.
