### ISSUE TITLE
enable build with c++11

### ISSUE THREAD

**Issue by onqtam** [BalazsJako/ImGuiColorTextEdit#9]
Hi! currently the source code requires c++14.
Only 2 lines of code have to be changed to enable c++11 builds - where ```std::equals()``` is used.

**Comment by BalazsJako** [comment]
Fixed. Please test.

**Comment by onqtam** [comment]
Well the code still calls ```std::equal``` and not just ```equal```. Also the new version of equal accepts 3 iterators and a predicate whereas the one from the ```std``` namespace accepts 4 iterators and a predicate

**Comment by BalazsJako** [comment]
Ah, sorry, my mistake.... Please try now.

**Comment by onqtam** [comment]
builds fine as C++11 - thanks!
